import FWCore.ParameterSet.Config as cms
ebyeana = cms.EDAnalyzer("EbyEAnalyzer",
                         nOrder = cms.untracked.double(2),
                         vertexTag_=cms.InputTag("hiSelectedVertex"),
                         CentralityTag_=cms.InputTag("hiCentrality"),
                         CentralityBinTag_=cms.InputTag("centralityBin","HFtowers"),
                         CentBinCompression_ = cms.untracked.int32(5),
                         trackTag_=cms.InputTag("hiGeneralTracks"),
                         caloCentRef_ = cms.untracked.double(80.),
                         caloCentRefWidth_ = cms.untracked.double(5.0),
                         loadDB_ = cms.untracked.bool(True),
                         minpt_ = cms.untracked.double(0.),
                         maxpt_ = cms.untracked.double(8.0),
                         etaMax_ = cms.untracked.double(2.4),
                         Branch_Cent = cms.untracked.bool(True),
                         Branch_Vtx = cms.untracked.bool(True),
                         Branch_sumw = cms.untracked.bool(True),
                         Branch_sumwqx = cms.untracked.bool(True),
                         Branch_sumwqy = cms.untracked.bool(True),
                         Branch_Run = cms.untracked.bool(True),
                         Subevent_Standard = cms.untracked.bool(True),
                         countHisto = cms.untracked.bool(False),
                         useTeff_ = cms.untracked.bool(True),
                         effTable_ = cms.string('')
                         )
